### ISSUE TITLE
Marmara Blockchain version change inside init script

### ISSUE THREAD

**Issue by rumeysayilmaz** [webworker01/nntools#11]
**Impacted version:** nntools master branch init file
**Links to the Current State:**
https://github.com/webworker01/nntools/blob/b85bf5e408e63de56f3e328b503f98e94d371f17/init#L265
https://github.com/webworker01/nntools/blob/b85bf5e408e63de56f3e328b503f98e94d371f17/init#L266
https://github.com/webworker01/nntools/blob/b85bf5e408e63de56f3e328b503f98e94d371f17/init#L267
https://github.com/webworker01/nntools/blob/b85bf5e408e63de56f3e328b503f98e94d371f17/init#L268
https://github.com/webworker01/nntools/blob/b85bf5e408e63de56f3e328b503f98e94d371f17/init#L269
https://github.com/webworker01/nntools/blob/b85bf5e408e63de56f3e328b503f98e94d371f17/init#L270

**Description of Current State:** The lines point to outdated version of Marmara blockchain. The expected change is suggested below.

**Expected Change:** Marmara should be built from the master branch as in provided below.
```
cd ~
git clone https://github.com/marmarachain/marmara --branch master --single-branch
cd marmara
./zcutil/fetch-params.sh
./zcutil/build.sh -j$(nproc) 
```

**Comment by webworker01** [comment]
Notary nodes use specific commits for third party repositories after the Komodo team has reviewed the code.  I will update when we have further info, but as of right now this is what is listed here: https://github.com/KomodoPlatform/dPoW/blob/master/README.md

**Comment by webworker01** [comment]
This has now been updated
